name: tools
run-name: ${{ github.actor }} is testing tools
on: [push, workflow_dispatch]
jobs:
    Run-snoopers:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: main
          - name: Check out data
            run: |
              eval $(ssh-agent -s)
              echo "${{ secrets.GH_WF }}" | ssh-add -
              ssh -T git@github.com   || true
              git clone git@github.com:chrisroederucdenver/CCDA-data.git
          - name: housekeeping,  change directory to prototype_2
            shell: bash
            run: |
                ln -s CCDA-data/resources .
                ls resources
                mkdir snooper_output
          - name: Run Code Snoopers
            run: |
                python3 section_code_snooper.py -d resources
                python3 header_code_snooper.py -d resources
                bin/compare_codes.sh

